/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diologoptions;

import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class DialogOptionsJFrame extends javax.swing.JFrame {
    
    //Yes/No/Cancel options
    Object[] yesNoCancelOptions = {"Yes", "No", "Cancel"};
    //Yes/No options
    Object[] yesNoOptions = {"Yes", "No"};   
    /**
     * Creates new form DialogOptionsJFrame
     */
    public DialogOptionsJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YesNoCancelButton = new javax.swing.JButton();
        YesNoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        YesNoCancelButton.setText("Yes/No/Cancel");
        YesNoCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesNoCancelButtonActionPerformed(evt);
            }
        });

        YesNoButton.setText("Yes/No");
        YesNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesNoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YesNoCancelButton)
                .addGap(18, 18, 18)
                .addComponent(YesNoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesNoCancelButton)
                    .addComponent(YesNoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesNoCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesNoCancelButtonActionPerformed
        int chosenOption = JOptionPane.showOptionDialog(null, "This is a Yes/No/Cancel option dialog pane.", "Yes/No/Cancel", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, yesNoCancelOptions, yesNoCancelOptions[2]);
        switch (chosenOption) {
            case 0 -> System.out.println("You chose yes.");
            case 1 -> System.out.println("You chose no.");
            case 2 -> System.out.println("You chose cancel.");
        }
    }//GEN-LAST:event_YesNoCancelButtonActionPerformed

    private void YesNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesNoButtonActionPerformed
        int chosenOption = JOptionPane.showOptionDialog(null, "This is a Yes/No option dialog pane.", "Yes/No", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, yesNoOptions, yesNoOptions[1]);
        if (chosenOption == 0) System.out.println("You chose yes.");
        else System.out.println("You chose no.");
    }//GEN-LAST:event_YesNoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogOptionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogOptionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogOptionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogOptionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogOptionsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton YesNoButton;
    private javax.swing.JButton YesNoCancelButton;
    // End of variables declaration//GEN-END:variables
}
