/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dialogmessages;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class DialogsWindowJFrame extends javax.swing.JFrame {
    
    /** Returns an ImageIcon, or null if the path was invalid. */
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = DialogsWindowJFrame.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    
    ImageIcon icon = createImageIcon("resources/rooster-g73d1b6346_640_red.png");
    
    /**
     * Creates new form DialogsWindowJFrame
     */
    public DialogsWindowJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageButton = new javax.swing.JButton();
        WarningButton = new javax.swing.JButton();
        ErrorButton = new javax.swing.JButton();
        PlainMessageButton = new javax.swing.JButton();
        CustomDialogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        messageButton.setText("Message");
        messageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageButtonActionPerformed(evt);
            }
        });

        WarningButton.setText("Warning");
        WarningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarningButtonActionPerformed(evt);
            }
        });

        ErrorButton.setText("Error");
        ErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorButtonActionPerformed(evt);
            }
        });

        PlainMessageButton.setText("Plain Message");
        PlainMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlainMessageButtonActionPerformed(evt);
            }
        });

        CustomDialogButton.setText("Custom Dialog");
        CustomDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageButton)
                        .addGap(18, 18, 18)
                        .addComponent(WarningButton)
                        .addGap(18, 18, 18)
                        .addComponent(ErrorButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlainMessageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustomDialogButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageButton)
                    .addComponent(WarningButton)
                    .addComponent(ErrorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlainMessageButton)
                    .addComponent(CustomDialogButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageButtonActionPerformed
        JOptionPane.showMessageDialog(null,"This is a message.");
    }//GEN-LAST:event_messageButtonActionPerformed

    private void ErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorButtonActionPerformed
        JOptionPane.showMessageDialog(null,"This is a error.","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ErrorButtonActionPerformed

    private void WarningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarningButtonActionPerformed
        JOptionPane.showMessageDialog(null, "This is a warning.", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_WarningButtonActionPerformed

    private void PlainMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlainMessageButtonActionPerformed
        JOptionPane.showMessageDialog(null, "This is a plain message.", "Plain Message", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_PlainMessageButtonActionPerformed

    private void CustomDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomDialogButtonActionPerformed
        JOptionPane.showMessageDialog(null,"This is a custom message.", "Custom Message", JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_CustomDialogButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogsWindowJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomDialogButton;
    private javax.swing.JButton ErrorButton;
    private javax.swing.JButton PlainMessageButton;
    private javax.swing.JButton WarningButton;
    private javax.swing.JButton messageButton;
    // End of variables declaration//GEN-END:variables
}
